INSERT INTO PRICE (ID, CURRENCY, PRICE, VEHICLE_ID) VALUES (1, 'USD', 50.5, 1)
INSERT INTO PRICE (ID, CURRENCY, PRICE, VEHICLE_ID) VALUES (2, 'USD', 3400.5, 2)
INSERT INTO PRICE (ID, CURRENCY, PRICE, VEHICLE_ID) VALUES (3, 'USD', 100.5, 3)